services:
  - type: web
    name: ivy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 3
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: ivy-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTORCH_ENABLE_MPS_FALLBACK
        value: "1"

databases:
  - name: ivy-db
    databaseName: ivy_prod
    user: ivy_user
    plan: standard

services:
  - type: redis
    name: ivy-cache
    ipAllowList: []
    plan: standard
    maxmemoryPolicy: noeviction 